"""
DBML (Database Markup Language) exporter.
Generates DBML from introspected schema metadata.

Produces two outputs:
1. Raw DBML - exact schema representation
2. Annotated DBML - with hints and user notes
"""

from dataclasses import dataclass
from typing import Optional

from app.core.models.schema import Column, Schema, Table


@dataclass
class TableAnnotation:
    """User-provided annotation for a table."""

    table_name: str
    is_likely_fact: bool = False
    is_likely_dimension: bool = False
    description: Optional[str] = None


class DBMLExporter:
    """
    Exports schema metadata to DBML format.

    DBML is a simple, readable DSL for defining database schemas.
    See: https://dbml.dbdiagram.io/docs/
    """

    def __init__(self, schema: Schema):
        self.schema = schema
        self.annotations: dict[str, TableAnnotation] = {}

    def add_annotation(self, annotation: TableAnnotation) -> None:
        """Add a user annotation for a table."""
        self.annotations[annotation.table_name] = annotation

    def export_raw(self) -> str:
        """
        Export raw DBML - exact schema representation without annotations.
        """
        lines = [f"// Schema: {self.schema.name}", "// Generated by Alens", ""]

        for table in self.schema.tables:
            lines.extend(self._export_table(table, include_annotations=False))
            lines.append("")

        # Add relationships (foreign keys)
        lines.append("// Relationships")
        for table in self.schema.tables:
            for fk in table.foreign_keys:
                ref_table = f"{fk.referenced_schema}.{fk.referenced_table}"
                for i, col in enumerate(fk.columns):
                    ref_col = (
                        fk.referenced_columns[i]
                        if i < len(fk.referenced_columns)
                        else fk.referenced_columns[0]
                    )
                    lines.append(
                        f"Ref: {table.full_name}.{col} > {ref_table}.{ref_col}"
                    )

        return "\n".join(lines)

    def export_annotated(self) -> str:
        """
        Export annotated DBML - includes user hints and notes.
        """
        lines = [
            f"// Schema: {self.schema.name}",
            "// Generated by Alens (Annotated)",
            "// Annotations are user-provided hints for dimensional modeling",
            "",
        ]

        for table in self.schema.tables:
            lines.extend(self._export_table(table, include_annotations=True))
            lines.append("")

        # Add relationships
        lines.append("// Relationships")
        for table in self.schema.tables:
            for fk in table.foreign_keys:
                ref_table = f"{fk.referenced_schema}.{fk.referenced_table}"
                for i, col in enumerate(fk.columns):
                    ref_col = (
                        fk.referenced_columns[i]
                        if i < len(fk.referenced_columns)
                        else fk.referenced_columns[0]
                    )
                    lines.append(
                        f"Ref: {table.full_name}.{col} > {ref_table}.{ref_col}"
                    )

        return "\n".join(lines)

    def _export_table(self, table: Table, include_annotations: bool) -> list[str]:
        """Export a single table to DBML format."""
        lines = []

        # Add annotation comments if available
        if include_annotations:
            annotation = self.annotations.get(table.name)
            if annotation:
                if annotation.is_likely_fact:
                    lines.append(f"// [HINT] Likely FACT table")
                if annotation.is_likely_dimension:
                    lines.append(f"// [HINT] Likely DIMENSION table")
                if annotation.description:
                    lines.append(f"// [NOTE] {annotation.description}")

            # Add auto-detected hints
            if table.has_timestamp_columns:
                lines.append(
                    f"// [AUTO] Contains timestamp columns - may be event-like"
                )
            if table.fk_count == 0:
                lines.append(
                    f"// [AUTO] No foreign keys - may be reference/lookup table"
                )
            elif table.fk_count >= 3:
                lines.append(
                    f"// [AUTO] Multiple FKs ({table.fk_count}) - may be fact table"
                )

        # Table definition
        table_note = f' [note: "{table.comment}"]' if table.comment else ""
        lines.append(f"Table {table.full_name}{table_note} {{")

        # Columns
        for col in table.columns:
            col_def = self._export_column(col)
            lines.append(f"  {col_def}")

        lines.append("}")
        return lines

    def _export_column(self, col: Column) -> str:
        """Export a single column to DBML format."""
        parts = [col.name, col.data_type]

        settings = []
        if col.is_primary_key:
            settings.append("pk")
        if not col.nullable:
            settings.append("not null")
        if col.default_value:
            # Clean up default value for DBML
            default = col.default_value.replace("'", "\\'")
            settings.append(f"default: '{default}'")
        if col.comment:
            note = col.comment.replace('"', '\\"')
            settings.append(f'note: "{note}"')

        if settings:
            parts.append(f"[{', '.join(settings)}]")

        return " ".join(parts)
